# Google Cloud Run Service Configuration
# This file defines the Cloud Run service specification

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: chickentracker
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        # Auto-scaling configuration
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '10'

        # CPU allocation (only allocated during request processing)
        run.googleapis.com/cpu-throttling: 'true'

        # VPC connector for Cloud SQL access
        # run.googleapis.com/vpc-access-connector: projects/PROJECT_ID/locations/REGION/connectors/CONNECTOR_NAME
        # run.googleapis.com/vpc-access-egress: private-ranges-only

        # Cloud SQL connection
        run.googleapis.com/cloudsql-instances: PROJECT_ID:REGION:DATABASE_INSTANCE_NAME

    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: SERVICE_ACCOUNT_EMAIL

      containers:
      - name: chickentracker
        image: gcr.io/PROJECT_ID/chickentracker:latest

        ports:
        - name: http1
          containerPort: 3000

        env:
        # Database
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-url
              key: latest

        # NextAuth
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: nextauth-secret
              key: latest

        - name: NEXTAUTH_URL
          value: https://chickentracker-XXXXX-uc.a.run.app

        # Node environment
        - name: NODE_ENV
          value: production

        resources:
          limits:
            # 1 CPU, 512MB RAM (adjust as needed)
            cpu: '1'
            memory: 512Mi
          requests:
            cpu: '1'
            memory: 512Mi
